### ISSUE TITLE
Is TypeScript available in the playground？

### ISSUE THREAD

**Issue by a20185** [wheatjs/vueuse-playground-next#1]

**Comment by a20185** [comment]
Great work of the playground!
After trying with the playground itself, I was wondering that if TypeScript is available in the Script Setup Section.
Or else is it possible?

**Comment by wheatjs** [comment]
Sorry, it is not currently available and there aren't currently plans to support it. Currently doing that kind of compilation can be quite difficult in the browser, but we may look more into it in the future.
